[package]
build = 'build.rs'
edition = '2018'
name = 'ton_executor'
version = '1.15.68'

[dependencies]
failure = '0.1.6'
lazy_static = '1.4.0'
log = '0.4'
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block.git', tag = '1.7.49' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.1' }
ton_vm = { git = 'https://github.com/tonlabs/ton-labs-vm.git', tag = '1.8.35' }


base64 = '0.10.0'
criterion = { features = [ 'html_reports' ], version = '0.3' }
rand = '0.8'
serde = { features = [ 'derive' ], version = '1.0' }
serde_json = '1.0'
ton_labs_assembler = { git = 'https://github.com/tonlabs/ton-labs-assembler.git', tag = '1.2.39' }
